import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white py-4">
          <div className="container mx-auto px-4 flex space-x-6">
            <a href="/dashboard" className="hover:text-gray-300">
              Dashboard
            </a>
            <a href="/projects" className="hover:text-gray-300">
              Projects
            </a>
            <a href="/persons" className="hover:text-gray-300">
              Team Members
            </a>
            <a href="/hardware" className="hover:text-gray-300">
              Hardware
            </a>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
